Repository skupperproject/skupper, pull requests merged in 2021-01, with the labels that each got.

#333 Move edge connectivity test to integration(#305)
  test/integration/edge_connectivity/edge_connectivity.go
  test/integration/edge_connectivity/edge_connectivity_test.go
Labels: enhancement, p0

#377 Updated Site type clone used by integration tests
  test/integration/annotation/annotated_resource_test.go
  test/integration/annotation/modification_functions.go
  test/utils/base/skupper.go
Labels: test

#360 Previous changes all together (skupper [token|link|service [bind|unbind]] and deprecations.
  Makefile
  cmd/skupper/skupper.go
  cmd/skupper/skupper_cluster_test.go
  cmd/skupper/skupper_link.go
  cmd/skupper/skupper_token.go
  test/integration/annotation/annotated_resource_test.go
Labels: cli-changes

#376 Fix name of secret printed in NewCmdStatus
  cmd/skupper/skupper.go
Labels: bug, p1
