Repository skupperproject/skupper, pull requests merged in 2023-03, with the labels that each got.

#1049 Fixed hostname in connect.json for podman sites
  pkg/domain/podman/credential_handler.go
Labels: bug

#968 Generate K8s events
  api/types/client.go
  client/router_create.go
  client/site_config_create.go
  client/site_config_inspect.go
  cmd/service-controller/console_server.go
  cmd/service-controller/controller.go
  cmd/service-controller/links.go
  cmd/service-controller/links_test.go
  cmd/service-controller/policy_controller.go
  cmd/service-controller/services.go
  cmd/service-controller/services_test.go
  cmd/service-controller/token_handler.go
  cmd/service-controller/token_handler_test.go
  cmd/site-controller/deploy-watch-all-ns.yaml
  cmd/site-controller/deploy-watch-current-ns.yaml
  cmd/skupper/skupper_kube_site.go
  go.mod
  go.sum
  pkg/event/event.go
  pkg/kube/events.go
  pkg/service_sync/messaging.go
  pkg/service_sync/messaging_test.go
  pkg/service_sync/service_sync.go
  pkg/service_sync/service_sync_test.go
Labels: enhancement

#1060 add the right link reference to the skupper console
  README.md
Labels: documentation

#1042 Podman site integration test
  .circleci/config.yml
  api/types/types.go
  test/integration/examples/custom/helloworld/helloworld_podman_test.go
  test/integration/examples/custom/helloworld/helloworld_test.go
  test/utils/skupper/cli/delete.go
  test/utils/skupper/cli/expose.go
  test/utils/skupper/cli/init.go
  test/utils/skupper/cli/service/bind.go
  test/utils/skupper/cli/service/create.go
  test/utils/skupper/cli/service/delete.go
  test/utils/skupper/cli/service/status.go
  test/utils/skupper/cli/service/unbind.go
  test/utils/skupper/cli/status.go
  test/utils/skupper/cli/tester.go
  test/utils/skupper/cli/unexpose.go
  test/utils/skupper/cli/verifier/http.go
  test/utils/skupper/cli/version.go
  test/utils/tools/curl.go
Labels: test, ci

#1065 Adjusting permissions needed by site controller
  cmd/site-controller/deploy-watch-all-ns.yaml
  cmd/site-controller/deploy-watch-current-ns.yaml
Labels: bug
