Repository skupperproject/skupper, pull requests merged in 2025-08, with the labels that each got.

#2231 update readme file
  charts/network-observer/README.md
Labels: documentation

#2235 Fixes race with Network Status Handler
  internal/nonkube/controller/network_status_handler.go
Labels: bug

#2202 Recreate updated link
  internal/qdr/amqp_mgmt.go
  internal/qdr/qdr.go
Labels: controller
